### ISSUE TITLE
Template translations with dynamic params are not correctly parsed/found

### ISSUE THREAD

**Issue by billdami** [bakerac4/vsc-ember-intl#1]
Given a `{{t}}` helper instance like the following:
```
{{t "foo.bar" baz="test"}}
```
Where `"foo.bar"` _does_ exist in the translations file, the extension will add the green squiggly "not found" underline to it, and a hover tooltip with the text:
```
Translations for foo.bar" baz="test:
en-us no translation
Missed translation in project
```
Additionally, if the dynamic params are not set to a string value (using quotes), e.g.
```
{{t "foo.bar" baz=test}}
```
The extension appears to skip/omit (or possible fails) parsing of the instance altogether, and produces no hover tooltip or intellisense suggestion (lightbulb button).

**Comment by bakerac4** [comment]
Fixed in #3
